name: Build and deploy Minoconda Strict

on:
  push:
    branches: ['main']
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: minoconda_strict
          registry: ${{ env.REGISTRY }}
          pushImage: true
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASS }}
          file: ./Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest